-- MySQL Script generated by MySQL Workbench
-- Sat Feb 23 19:00:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistemadomotico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistemadomotico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemadomotico` DEFAULT CHARACTER SET latin1 ;
USE `sistemadomotico` ;

-- -----------------------------------------------------
-- Table `sistemadomotico`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`administrador` (
  `idAdministrador` INT(11) NOT NULL,
  `N_identificacion` INT(11) NULL DEFAULT NULL,
  `Contraseña` NCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistemadomotico`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`perfil` (
  `idperfil` INT(11) NOT NULL,
  `N_identificacion` INT(11) NULL DEFAULT NULL,
  `Nom_perfil` VARCHAR(45) NULL DEFAULT NULL,
  `Ape_perfil` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha` VARCHAR(45) NULL DEFAULT NULL,
  `Dir_residencia` VARCHAR(45) NULL DEFAULT NULL,
  `Sexo` VARCHAR(45) NULL DEFAULT NULL,
  `menu_idMenu` INT(11) NOT NULL,
  PRIMARY KEY (`idperfil`),
  INDEX `fk_perfil_menu1_idx` (`menu_idMenu` ASC),
  CONSTRAINT `fk_perfil_menu1`
    FOREIGN KEY (`menu_idMenu`)
    REFERENCES `sistemadomotico`.`menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistemadomotico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`usuario` (
  `idUsuario` INT(11) NOT NULL,
  `Tipo_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `menu_idMenu` INT(11) NOT NULL,
  `perfil_idperfil` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_menu1_idx` (`menu_idMenu` ASC),
  INDEX `fk_usuario_perfil1_idx` (`perfil_idperfil` ASC),
  CONSTRAINT `fk_usuario_menu1`
    FOREIGN KEY (`menu_idMenu`)
    REFERENCES `sistemadomotico`.`menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `sistemadomotico`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistemadomotico`.`iniciar sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`iniciar sesion` (
  `idiniciar sesion` INT(11) NOT NULL AUTO_INCREMENT,
  `N_identificacion` INT(11) NOT NULL,
  `Contraseña` NCHAR(32) NOT NULL,
  `administrador_idAdministrador` INT(11) NOT NULL,
  `usuario_idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idiniciar sesion`),
  INDEX `fk_iniciar sesion_administrador_idx` (`administrador_idAdministrador` ASC),
  INDEX `fk_iniciar sesion_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_iniciar sesion_administrador`
    FOREIGN KEY (`administrador_idAdministrador`)
    REFERENCES `sistemadomotico`.`administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iniciar sesion_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `sistemadomotico`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistemadomotico`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`menu` (
  `idMenu` INT(11) NOT NULL AUTO_INCREMENT,
  `iniciar sesion_idiniciar sesion` INT(11) NOT NULL,
  PRIMARY KEY (`idMenu`),
  INDEX `fk_menu_iniciar sesion1_idx` (`iniciar sesion_idiniciar sesion` ASC),
  CONSTRAINT `fk_menu_iniciar sesion1`
    FOREIGN KEY (`iniciar sesion_idiniciar sesion`)
    REFERENCES `sistemadomotico`.`iniciar sesion` (`idiniciar sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistemadomotico`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`dispositivo` (
  `idDispositivo` INT(11) NOT NULL,
  `Nom_dispositivo` VARCHAR(45) NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Tipo` VARCHAR(45) NULL DEFAULT NULL,
  `Estados` VARCHAR(45) NULL DEFAULT NULL,
  `Condicion` VARCHAR(45) NULL DEFAULT NULL,
  `menu_idMenu` INT(11) NOT NULL,
  PRIMARY KEY (`idDispositivo`),
  INDEX `fk_dispositivo_menu1_idx` (`menu_idMenu` ASC),
  CONSTRAINT `fk_dispositivo_menu1`
    FOREIGN KEY (`menu_idMenu`)
    REFERENCES `sistemadomotico`.`menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistemadomotico`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`estados` (
  `idEstados` INT(11) NOT NULL,
  `menu_idMenu` INT(11) NOT NULL,
  `dispositivo_idDispositivo` INT(11) NOT NULL,
  PRIMARY KEY (`idEstados`),
  INDEX `fk_estados_menu1_idx` (`menu_idMenu` ASC),
  INDEX `fk_estados_dispositivo1_idx` (`dispositivo_idDispositivo` ASC),
  CONSTRAINT `fk_estados_menu1`
    FOREIGN KEY (`menu_idMenu`)
    REFERENCES `sistemadomotico`.`menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estados_dispositivo1`
    FOREIGN KEY (`dispositivo_idDispositivo`)
    REFERENCES `sistemadomotico`.`dispositivo` (`idDispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistemadomotico`.`alarma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`alarma` (
  `idAlarma` INT(11) NOT NULL,
  `Actuador` INT(11) NULL DEFAULT NULL,
  `menu_idMenu` INT(11) NOT NULL,
  `estados_idEstados` INT(11) NOT NULL,
  PRIMARY KEY (`idAlarma`),
  INDEX `fk_alarma_menu1_idx` (`menu_idMenu` ASC),
  INDEX `fk_alarma_estados1_idx` (`estados_idEstados` ASC),
  CONSTRAINT `fk_alarma_menu1`
    FOREIGN KEY (`menu_idMenu`)
    REFERENCES `sistemadomotico`.`menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alarma_estados1`
    FOREIGN KEY (`estados_idEstados`)
    REFERENCES `sistemadomotico`.`estados` (`idEstados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sistemadomotico`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemadomotico`.`eventos` (
  `idEventos` INT(11) NOT NULL,
  `Hora_entrada` DATE NULL DEFAULT NULL,
  `Hora_salida` DATE NULL DEFAULT NULL,
  `Dias_habiles` INT(11) NULL DEFAULT NULL,
  `Eventoscol` VARCHAR(45) NULL DEFAULT NULL,
  `menu_idMenu` INT(11) NOT NULL,
  PRIMARY KEY (`idEventos`),
  INDEX `fk_eventos_menu1_idx` (`menu_idMenu` ASC),
  CONSTRAINT `fk_eventos_menu1`
    FOREIGN KEY (`menu_idMenu`)
    REFERENCES `sistemadomotico`.`menu` (`idMenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
