-- MySQL Script generated by MySQL Workbench
-- Mon Feb 25 22:14:14 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema techdomotica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema techdomotica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techdomotica` ;
USE `techdomotica` ;

-- -----------------------------------------------------
-- Table `techdomotica`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`menu` (
  `idmenu` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techdomotica`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`perfil` (
  `idperfil` INT NOT NULL,
  `nom_perfil` VARCHAR(45) NULL,
  `ape_perfil` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `menu_idmenu` INT NOT NULL,
  PRIMARY KEY (`idperfil`),
  INDEX `fk_perfil_menu1_idx` (`menu_idmenu` ASC),
  CONSTRAINT `fk_perfil_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `techdomotica`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techdomotica`.`iniciar sesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`iniciar sesion` (
  `idiniciar sesion` INT NOT NULL AUTO_INCREMENT,
  `clave` INT NULL,
  `perfil_idperfil` INT NOT NULL,
  `menu_idmenu` INT NOT NULL,
  PRIMARY KEY (`idiniciar sesion`),
  INDEX `fk_iniciar sesion_perfil_idx` (`perfil_idperfil` ASC),
  INDEX `fk_iniciar sesion_menu1_idx` (`menu_idmenu` ASC),
  CONSTRAINT `fk_iniciar sesion_perfil`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `techdomotica`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_iniciar sesion_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `techdomotica`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techdomotica`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`dispositivo` (
  `iddispositivo` INT NOT NULL AUTO_INCREMENT,
  `nom_dispositivo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `condicion` VARCHAR(45) NULL,
  `menu_idmenu` INT NOT NULL,
  PRIMARY KEY (`iddispositivo`),
  INDEX `fk_dispositivo_menu1_idx` (`menu_idmenu` ASC),
  CONSTRAINT `fk_dispositivo_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `techdomotica`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techdomotica`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`estados` (
  `idestados` INT NOT NULL AUTO_INCREMENT,
  `menu_idmenu` INT NOT NULL,
  `dispositivo_iddispositivo` INT NOT NULL,
  PRIMARY KEY (`idestados`),
  INDEX `fk_estados_menu1_idx` (`menu_idmenu` ASC),
  INDEX `fk_estados_dispositivo1_idx` (`dispositivo_iddispositivo` ASC),
  CONSTRAINT `fk_estados_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `techdomotica`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estados_dispositivo1`
    FOREIGN KEY (`dispositivo_iddispositivo`)
    REFERENCES `techdomotica`.`dispositivo` (`iddispositivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techdomotica`.`alarma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`alarma` (
  `idalarma` INT NOT NULL AUTO_INCREMENT,
  `actuador` INT NULL,
  `estados_idestados` INT NOT NULL,
  `menu_idmenu` INT NOT NULL,
  PRIMARY KEY (`idalarma`),
  INDEX `fk_alarma_estados1_idx` (`estados_idestados` ASC),
  INDEX `fk_alarma_menu1_idx` (`menu_idmenu` ASC),
  CONSTRAINT `fk_alarma_estados1`
    FOREIGN KEY (`estados_idestados`)
    REFERENCES `techdomotica`.`estados` (`idestados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alarma_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `techdomotica`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techdomotica`.`tipo_reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`tipo_reporte` (
  `idtipo_reporte` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipo_reporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techdomotica`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`reporte` (
  `idreporte` INT NOT NULL AUTO_INCREMENT,
  `hora` TIMESTAMP NULL,
  `fecha` DATETIME NULL,
  `perfil_idperfil` INT NOT NULL,
  `tipo_reporte_idtipo_reporte` INT NOT NULL,
  PRIMARY KEY (`idreporte`),
  INDEX `fk_reporte_perfil1_idx` (`perfil_idperfil` ASC),
  INDEX `fk_reporte_tipo_reporte1_idx` (`tipo_reporte_idtipo_reporte` ASC),
  CONSTRAINT `fk_reporte_perfil1`
    FOREIGN KEY (`perfil_idperfil`)
    REFERENCES `techdomotica`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_tipo_reporte1`
    FOREIGN KEY (`tipo_reporte_idtipo_reporte`)
    REFERENCES `techdomotica`.`tipo_reporte` (`idtipo_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techdomotica`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `techdomotica`.`eventos` (
  `ideventos` INT NOT NULL AUTO_INCREMENT,
  `menu_idmenu` INT NOT NULL,
  `reporte_idreporte` INT NOT NULL,
  PRIMARY KEY (`ideventos`),
  INDEX `fk_eventos_menu1_idx` (`menu_idmenu` ASC),
  INDEX `fk_eventos_reporte1_idx` (`reporte_idreporte` ASC),
  CONSTRAINT `fk_eventos_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `techdomotica`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eventos_reporte1`
    FOREIGN KEY (`reporte_idreporte`)
    REFERENCES `techdomotica`.`reporte` (`idreporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
