package techdomotica.java.forms.security;

import javax.swing.JOptionPane;
import techdomotica.objs.Ambiente;
import techdomotica.objs.Reporte;

/**
 *
 * @author Andres
 */
public class SecurityAddRep extends javax.swing.JDialog {

    private Ambiente ambiente;
   
    public SecurityAddRep(java.awt.Frame parent, boolean modal, Ambiente amb) {
        super(parent, modal);
        ambiente = amb;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaReport = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        charLim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir reporte - Tech Domótica");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Reporte rápido");

        areaReport.setColumns(20);
        areaReport.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        areaReport.setRows(5);
        areaReport.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                areaReportKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                areaReportKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(areaReport);

        jButton1.setText("Agregar reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        charLim.setText("Límite de caracteres: 0/1000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(charLim, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charLim)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!areaReport.getText().isEmpty()) {
            if(Reporte.insertReport(Integer.parseInt(ambiente.getAdminEncargado().getID()), 8, areaReport.getText()) == 1) {
                JOptionPane.showMessageDialog(null, "Se ha guardado el reporte de manera exitosa.", "Éxito en la operación", JOptionPane.INFORMATION_MESSAGE);
                int conf = JOptionPane.showConfirmDialog(null, "¿Deseas seguir añadiendo más reportes?", "¿Agregar nuevo reporte?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(conf == JOptionPane.YES_OPTION) {
                    areaReport.setText("");
                    areaReport.requestFocus();
                }
                else {
                    this.dispose();
                }
            }
            else JOptionPane.showMessageDialog(null, "Ha ocurrido al momento de guardar el reporte. Intentalo más tarde.", "Error en la operación", JOptionPane.ERROR_MESSAGE);
        }
        else JOptionPane.showMessageDialog(null, "No puedes enviar un reporte vacío.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void areaReportKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaReportKeyPressed
        
    }//GEN-LAST:event_areaReportKeyPressed

    private void areaReportKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaReportKeyTyped
        String currentText = areaReport.getText();
        if(currentText.length() >= 1000) {
            String realText = currentText.substring(0, 999);
            areaReport.setText(realText);
        }
        charLim.setText(String.format("Límite de caracteres: %d/1000", currentText.length()));
    }//GEN-LAST:event_areaReportKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityAddRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityAddRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityAddRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityAddRep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SecurityAddRep dialog = new SecurityAddRep(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaReport;
    private javax.swing.JLabel charLim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
